### ISSUE TITLE
Roadmap for Julia push

### ISSUE THREAD

**Issue by albop** [EconForge/Dolo.jl#28]
@anasza, @jagman88, @spencerlyon2 

I have just merged into master, our work with @anasza. There is *one* implementation of `time_iteration_direct`, `time_iteration`, `value_iteration` which all work for any type of shock, thanks to new decision rules objects (look in `test/test_algos.jl` ) . Modulo a few possible improvements, it feels just like the right approach. I have listed below the pieces we still need to implement to get a fully working version: (more details in https://github.com/EconForge/Dolo.jl/wiki/ROADMAP)

- [ ] Simulate methods for all processes
- [ ] Simulate a model with a solution
- [ ] AR1 decision rule
- Solution algorithms
    - [ ] VFI (cleanup)
    - [ ] PEA
    - [ ] perturbation (requires fix to AR1)
- [ ] Distribution object
- Ergodic distribution
    - [ ] Simulation based
    - [ ] By finding the fixed point of a discrete Markov Chain.
- [ ] Accuracy measures

**Comment by spencerlyon2** [comment]
This is really cool! I don't think the merged master branch has been pushed to github yet, but I checked it out on the other branch.

I don't have the time to go through it carefully right now, but I will be doing that at some point.

**Comment by albop** [comment]
Indeed, I didn't push the merged version. Done.
